// Code generated by mockery v2.52.2. DO NOT EDIT.

package hubapi_mocks

import (
	context "context"

	pluginapiv1 "github.com/blackstork-io/blackstork-cli/plugin/pluginapi/v1"
	hubapi "github.com/blackstork-io/blackstork-cli/plugins/builtin/hubapi"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// UploadDocument provides a mock function with given fields: ctx, doc
func (_m *Client) UploadDocument(ctx context.Context, doc *pluginapiv1.Document) (*hubapi.HubDocument, error) {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for UploadDocument")
	}

	var r0 *hubapi.HubDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pluginapiv1.Document) (*hubapi.HubDocument, error)); ok {
		return rf(ctx, doc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pluginapiv1.Document) *hubapi.HubDocument); ok {
		r0 = rf(ctx, doc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hubapi.HubDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pluginapiv1.Document) error); ok {
		r1 = rf(ctx, doc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_UploadDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadDocument'
type Client_UploadDocument_Call struct {
	*mock.Call
}

// UploadDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - doc *pluginapiv1.Document
func (_e *Client_Expecter) UploadDocument(ctx interface{}, doc interface{}) *Client_UploadDocument_Call {
	return &Client_UploadDocument_Call{Call: _e.mock.On("UploadDocument", ctx, doc)}
}

func (_c *Client_UploadDocument_Call) Run(run func(ctx context.Context, doc *pluginapiv1.Document)) *Client_UploadDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pluginapiv1.Document))
	})
	return _c
}

func (_c *Client_UploadDocument_Call) Return(_a0 *hubapi.HubDocument, _a1 error) *Client_UploadDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_UploadDocument_Call) RunAndReturn(run func(context.Context, *pluginapiv1.Document) (*hubapi.HubDocument, error)) *Client_UploadDocument_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
