version: "2"
run:
  tests: false
output:
  path-prefix: ""
linters:
  default: none
  enable:
    - gocritic
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - ifElseChain
        - wrapperFunc
        - hugeParam
        - rangeValCopy
        - appendCombine
        - commentedOutCode
        - sloppyReassign
        - filepathJoin
        - evalOrder
        - equalFold
        - returnAfterHttpError
        - preferStringWriter
        - sprintfQuotedString
        - preferFprint
      enabled-tags:
        - diagnostic
        - performance
    goheader:
      template: |-
        Copyright 2026 BlackStork BV

        Use of this software is governed by the Business Source License included in the
        file LICENSE and at www.mariadb.com/bsl11.

        As of the Change Date specified in that file, in accordance with the Business
        Source License, use of this software will be governed by the Apache License,
        Version 2.0, included in the file .licenses/APACHE-2.0.txt.
    govet:
      disable:
        - shadow
    nolintlint:
      require-explanation: false
      require-specific: false
    staticcheck:
      checks:
        - all
        - -SA1019
  exclusions:
    generated: lax
    paths:
      - (^|/)vendor($|/)
      - (^|/)third_party($|/)
      - (^|/)testdata($|/)
      - (^|/)examples($|/)
      - (^|/)Godeps($|/)
      - third_party$
      - builtin$
      - examples$
      - (^|/)tmp($|/)
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/blackstork-io/blackstork-cli)
    goimports:
      local-prefixes:
        - github.com/blackstork-io/blackstork-cli
  exclusions:
    generated: lax
    paths:
      - (^|/)vendor($|/)
      - (^|/)third_party($|/)
      - (^|/)testdata($|/)
      - (^|/)examples($|/)
      - (^|/)Godeps($|/)
      - third_party$
      - builtin$
      - examples$
      - (^|/)tmp($|/)
