# Copyright 2026 BlackStork BV
#
# Use of this software is governed by the Business Source License included in the
# file LICENSE and at www.mariadb.com/bsl11.
#
# As of the Change Date specified in that file, in accordance with the Business
# Source License, use of this software will be governed by the Apache License,
# Version 2.0, included in the file .licenses/APACHE-2.0.txt.

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: blackstork-cli

env:
  - CGO_ENABLED=0

snapshot:
  version_template: "{{ .Version }}-dev"

builds:
  # CLI
  - id: blackstork-cli
    main: .
    binary: blackstork-cli
    ldflags:
      - -X github.com/blackstork-io/blackstork-cli/cmd.version={{.Version}}
      - -X github.com/blackstork-io/blackstork-cli/cmd.builtBy=goreleaser
    gcflags: all=-N -l
    no_unique_dist_dir: true

  # Plugins

  - id: elastic
    main: ./plugins/elastic/cmd
    binary: "plugins/blackstork/elastic@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: eclecticiq
    main: ./plugins/eclecticiq/cmd
    binary: "plugins/blackstork/eclecticiq@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: github
    main: ./plugins/github/cmd
    binary: "plugins/blackstork/github@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: graphql
    main: ./plugins/graphql/cmd
    binary: "plugins/blackstork/graphql@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: openai
    main: ./plugins/openai/cmd
    binary: "plugins/blackstork/openai@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: opencti
    main: ./plugins/opencti/cmd
    binary: "plugins/blackstork/opencti@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: nistnvd
    main: ./plugins/nistnvd/cmd
    binary: "plugins/blackstork/nist_nvd@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: postgresql
    main: ./plugins/postgresql/cmd
    binary: "plugins/blackstork/postgresql@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: sqlite
    main: ./plugins/sqlite/cmd
    binary: "plugins/blackstork/sqlite@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: terraform
    main: ./plugins/terraform/cmd
    binary: "plugins/blackstork/terraform@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: hackerone
    main: ./plugins/hackerone/cmd
    binary: "plugins/blackstork/hackerone@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: virustotal
    main: ./plugins/virustotal/cmd
    binary: "plugins/blackstork/virustotal@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: splunk
    main: ./plugins/splunk/cmd
    binary: "plugins/blackstork/splunk@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: stixview
    main: ./plugins/stixview/cmd
    binary: "plugins/blackstork/stixview@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: snyk
    main: ./plugins/snyk/cmd
    binary: "plugins/blackstork/snyk@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: microsoft
    main: ./plugins/microsoft/cmd
    binary: "plugins/blackstork/microsoft@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: iris
    main: ./plugins/iris/cmd
    binary: "plugins/blackstork/iris@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: atlassian
    main: ./plugins/atlassian/cmd
    binary: "plugins/blackstork/atlassian@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin

  - id: MISP
    main: ./plugins/misp/cmd
    binary: "plugins/blackstork/misp@{{ .Version }}"
    ldflags: "-X main.version={{.Version}}"
    gcflags: all=-N -l
    no_unique_dist_dir: true
    tags:
      - blackstorkplugin
