# Copyright 2026 BlackStork BV
#
# Use of this software is governed by the Business Source License included in the
# file LICENSE and at www.mariadb.com/bsl11.
#
# As of the Change Date specified in that file, in accordance with the Business
# Source License, use of this software will be governed by the Apache License,
# Version 2.0, included in the file .licenses/APACHE-2.0.txt.

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: blackstork-cli

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}}

builds:
  # CLI

  - id: blackstork-cli
    main: .
    binary: blackstork-cli
    flags: "-trimpath"
    ldflags:
      - -s -w
      - -X github.com/blackstork-io/blackstork-cli/cmd.version={{.Version}}
      - -X github.com/blackstork-io/blackstork-cli/cmd.builtBy=goreleaser

    targets:
      - linux_amd64_v1
      - linux_arm64 # implicitly v8
      - darwin_amd64_v1
      - darwin_arm64
      - windows_amd64_v1
      - windows_arm64


  # Plugins
  # TODO: generate this list with custom script or use Premium goreleaser to template it

  - id: plugin_elastic
    main: ./plugins/elastic/cmd
    binary: "elastic@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_eclecticiq
    main: ./plugins/eclecticiq/cmd
    binary: "eclecticiq@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_github
    main: ./plugins/github/cmd
    binary: "github@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_graphql
    main: ./plugins/graphql/cmd
    binary: "graphql@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_openai
    main: ./plugins/openai/cmd
    binary: "openai@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_nist_nvd
    main: ./plugins/nistnvd/cmd
    binary: "nist_nvd@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_opencti
    main: ./plugins/opencti/cmd
    binary: "opencti@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_postgresql
    main: ./plugins/postgresql/cmd
    binary: "postgresql@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_sqlite
    main: ./plugins/sqlite/cmd
    binary: "sqlite@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_terraform
    main: ./plugins/terraform/cmd
    binary: "terraform@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_hackerone
    main: ./plugins/hackerone/cmd
    binary: "hackerone@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_virustotal
    main: ./plugins/virustotal/cmd
    binary: "virustotal@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_splunk
    main: ./plugins/splunk/cmd
    binary: "splunk@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_stixview
    main: ./plugins/stixview/cmd
    binary: "stixview@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_snyk
    main: ./plugins/snyk/cmd
    binary: "snyk@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_microsoft
    main: ./plugins/microsoft/cmd
    binary: "microsoft@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_iris
    main: ./plugins/iris/cmd
    binary: "iris@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

  - id: plugin_atlassian
    main: ./plugins/atlassian/cmd
    binary: "atlassian@{{ .Version }}"
    flags: "-trimpath"
    hooks:
      post:
        - go run ./tools/pluginmeta --namespace blackstork --version {{.Version}} patch --plugin {{.Path}} --os {{.Os}} --arch {{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    tags:
      - blackstorkplugin

archives:
  - id: blackstork-cli
    format: tar.gz
    builds:
      - blackstork-cli
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

  # Plugins
  # TODO: generate this list with custom script or use Premium goreleaser to template it

  - id: plugin_elastic
    format: tar.gz
    builds:
      - plugin_elastic
    name_template: >-
      plugin_elastic_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_eclecticiq
    format: tar.gz
    builds:
      - plugin_eclecticiq
    name_template: >-
      plugin_eclecticiq_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_github
    format: tar.gz
    builds:
      - plugin_github
    name_template: >-
      plugin_github_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_graphql
    format: tar.gz
    builds:
      - plugin_graphql
    name_template: >-
      plugin_graphql_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_openai
    format: tar.gz
    builds:
      - plugin_openai
    name_template: >-
      plugin_openai_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_opencti
    format: tar.gz
    builds:
      - plugin_opencti
    name_template: >-
      plugin_opencti_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_postgresql
    format: tar.gz
    builds:
      - plugin_postgresql
    name_template: >-
      plugin_postgresql_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_sqlite
    format: tar.gz
    builds:
      - plugin_sqlite
    name_template: >-
      plugin_sqlite_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_terraform
    format: tar.gz
    builds:
      - plugin_terraform
    name_template: >-
      plugin_terraform_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_hackerone
    format: tar.gz
    builds:
      - plugin_hackerone
    name_template: >-
      plugin_hackerone_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_virustotal
    format: tar.gz
    builds:
      - plugin_virustotal
    name_template: >-
      plugin_virustotal_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_splunk
    format: tar.gz
    builds:
      - plugin_splunk
    name_template: >-
      plugin_splunk_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_stixview
    format: tar.gz
    builds:
      - plugin_stixview
    name_template: >-
      plugin_stixview_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_nist_nvd
    format: tar.gz
    builds:
      - plugin_nist_nvd
    name_template: >-
      plugin_nist_nvd_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: plugin_snyk
    format: tar.gz
    builds:
      - plugin_snyk
    name_template: >-
      plugin_snyk_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: plugin_microsoft
    format: tar.gz
    builds:
      - plugin_microsoft
    name_template: >-
      plugin_microsoft_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_iris
    format: tar.gz
    builds:
      - plugin_iris
    name_template: >-
      plugin_iris_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: plugin_atlassian
    format: tar.gz
    builds:
      - plugin_atlassian
    name_template: >-
      plugin_atlassian_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

# dockers:
#   - use: buildx
#     goos: linux
#     goarch: amd64
#     goamd64: v1
#     ids:
#       - blackstork-cli
#     image_templates:
#       - "{{ .Env.CONTAINER_REPO_NAME }}:latest-amd64v1"
#     build_flag_templates:
#       - "--platform=linux/amd64/v1"
#   - use: buildx
#     goos: linux
#     goarch: arm64
#     ids:
#       - blackstork-cli
#     image_templates:
#       - "{{ .Env.CONTAINER_REPO_NAME }}:latest-arm64v8"
#     build_flag_templates:
#       - "--platform=linux/arm64/v8"
#   - use: buildx
#     goos: linux
#     goarch: "386"
#     ids:
#       - blackstork-cli
#     image_templates:
#       - "{{ .Env.CONTAINER_REPO_NAME }}:latest-386"
#     build_flag_templates:
#       - "--platform=linux/386"

# docker_manifests:
#   - name_template: "{{ .Env.CONTAINER_REPO_NAME }}:{{ .Version }}"
#     image_templates:
#     - "{{ .Env.CONTAINER_REPO_NAME }}:latest-amd64v1"
#     - "{{ .Env.CONTAINER_REPO_NAME }}:latest-arm64v8"
#     - "{{ .Env.CONTAINER_REPO_NAME }}:latest-386"
#   - name_template: "{{ .Env.CONTAINER_REPO_NAME }}:latest"
#     image_templates:
#     - "{{ .Env.CONTAINER_REPO_NAME }}:latest-amd64v1"
#     - "{{ .Env.CONTAINER_REPO_NAME }}:latest-arm64v8"
#     - "{{ .Env.CONTAINER_REPO_NAME }}:latest-386"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: blackstork-cli
    ids:
      - blackstork-cli
    description: "A source-available, headless execution engine for BlackStork templates. It automates cybersecurity and compliance reporting by generating Markdown, HTML and PDF reports from structured data using modular declarative templates."
    homepage: "https://blackstork.io/cli/"
    license: BUSL-1.1
    repository:
      owner: blackstork-io
      name: homebrew-tools
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

release:
  extra_files:
    - glob: ./.tmp/plugins.json
  prerelease: auto
