# Copyright 2026 BlackStork BV
#
# Use of this software is governed by the Business Source License included in the
# file LICENSE and at www.mariadb.com/bsl11.
#
# As of the Change Date specified in that file, in accordance with the Business
# Source License, use of this software will be governed by the Apache License,
# Version 2.0, included in the file .licenses/APACHE-2.0.txt.

# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
default: true   # enable all by default
MD007:          # unordered list indentation
  indent: 2
MD013: false    # do not validate line length
MD014: false    # allow $ before command output
MD024: false    # allow duplicate headings, for example, "Example"
MD029:          # ordered list prefix, use all ones
  style: "one"
MD033: false    # allow inline HTML
MD041: false    # the first line is not always H1
MD025: false    # because it thinks that is there is frontmatter, there should be no H1
