# Copyright 2026 BlackStork BV
#
# Use of this software is governed by the Business Source License included in the
# file LICENSE and at www.mariadb.com/bsl11.
#
# As of the Change Date specified in that file, in accordance with the Business
# Source License, use of this software will be governed by the Apache License,
# Version 2.0, included in the file .licenses/APACHE-2.0.txt.

with-expecter: true
dir: mocks/{{ .InterfaceDirRelative }}
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mocks"
filename: "{{.InterfaceName | snakecase}}.go"
resolve-type-alias: False
issue-845-fix: true
packages:
  github.com/blackstork-io/fabric/specs/definitions:
    config:
      recursive: true
    interfaces:
      BlockDef:
  github.com/blackstork-io/fabric/plugins/github:
    config:
    interfaces:
      Client:
      IssuesClient:
      GistClient:
  github.com/blackstork-io/fabric/plugins/openai/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugins/hackerone/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugins/virustotal/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugins/splunk/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugins/nistnvd/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugins/iris/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugins/elastic/kbclient:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugins/snyk/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugins/builtin/hubapi:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugins/microsoft:
    config:
    interfaces:
      AzureClient:
      AzureOpenAIClient:
      MicrosoftGraphClient:
      MicrosoftSecurityClient:
  github.com/blackstork-io/fabric/plugins/atlassian/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugins/crowdstrike:
    config:
    interfaces:
      Client:
      CspmRegistrationClient:
      DetectsClient:
      SpotVulnerabilitiesClient:
      IntelClient:
      DiscoverClient:
  github.com/blackstork-io/fabric/plugins/misp:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugin/resolver:
    config:
      inpackage: true
      dir: "./plugin/resolver"
      mockname: "mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      filename: "mock_{{.InterfaceName | snakecase}}_test.go"
    interfaces:
      Source:
