// Copyright 2026 BlackStork BV
//
// Use of this software is governed by the Business Source License included in the
// file LICENSE and at www.mariadb.com/bsl11.
//
// As of the Change Date specified in that file, in accordance with the Business
// Source License, use of this software will be governed by the Apache License,
// Version 2.0, included in the file .licenses/APACHE-2.0.txt.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluginapi/v1/content.proto

package pluginapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentProviderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentProviderResult) Reset() {
	*x = ContentProviderResult{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentProviderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentProviderResult) ProtoMessage() {}

func (x *ContentProviderResult) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentProviderResult.ProtoReflect.Descriptor instead.
func (*ContentProviderResult) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentProviderResult) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Content_Element
	//	*Content_Section
	Value         isContent_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *Content) GetValue() isContent_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Content) GetElement() *ContentElement {
	if x != nil {
		if x, ok := x.Value.(*Content_Element); ok {
			return x.Element
		}
	}
	return nil
}

func (x *Content) GetSection() *ContentSection {
	if x != nil {
		if x, ok := x.Value.(*Content_Section); ok {
			return x.Section
		}
	}
	return nil
}

type isContent_Value interface {
	isContent_Value()
}

type Content_Element struct {
	Element *ContentElement `protobuf:"bytes,1,opt,name=element,proto3,oneof"`
}

type Content_Section struct {
	Section *ContentSection `protobuf:"bytes,2,opt,name=section,proto3,oneof"`
}

func (*Content_Element) isContent_Value() {}

func (*Content_Section) isContent_Value() {}

type BlockDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Runner        string                 `protobuf:"bytes,2,opt,name=runner,proto3" json:"runner,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Depth         uint32                 `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDetails) Reset() {
	*x = BlockDetails{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDetails) ProtoMessage() {}

func (x *BlockDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDetails.ProtoReflect.Descriptor instead.
func (*BlockDetails) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *BlockDetails) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *BlockDetails) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *BlockDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlockDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockDetails) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type ExecDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	PluginVersion string                 `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	Runner        string                 `protobuf:"bytes,3,opt,name=runner,proto3" json:"runner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecDetails) Reset() {
	*x = ExecDetails{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecDetails) ProtoMessage() {}

func (x *ExecDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecDetails.ProtoReflect.Descriptor instead.
func (*ExecDetails) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *ExecDetails) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *ExecDetails) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *ExecDetails) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

type ContentSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockDetails  *BlockDetails          `protobuf:"bytes,1,opt,name=block_details,json=blockDetails,proto3" json:"block_details,omitempty"`
	Meta          *MapData               `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Title         *Content               `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Children      []*Content             `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	Id            []byte                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentSection) Reset() {
	*x = ContentSection{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentSection) ProtoMessage() {}

func (x *ContentSection) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentSection.ProtoReflect.Descriptor instead.
func (*ContentSection) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *ContentSection) GetBlockDetails() *BlockDetails {
	if x != nil {
		return x.BlockDetails
	}
	return nil
}

func (x *ContentSection) GetMeta() *MapData {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ContentSection) GetTitle() *Content {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *ContentSection) GetChildren() []*Content {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ContentSection) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ContentElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockDetails  *BlockDetails          `protobuf:"bytes,1,opt,name=block_details,json=blockDetails,proto3" json:"block_details,omitempty"`
	ExecDetails   *ExecDetails           `protobuf:"bytes,2,opt,name=exec_details,json=execDetails,proto3" json:"exec_details,omitempty"`
	Meta          *MapData               `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Attrs         *MapData               `protobuf:"bytes,5,opt,name=attrs,proto3" json:"attrs,omitempty"`
	DataContext   *MapData               `protobuf:"bytes,6,opt,name=data_context,json=dataContext,proto3" json:"data_context,omitempty"`
	Id            []byte                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentElement) Reset() {
	*x = ContentElement{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentElement) ProtoMessage() {}

func (x *ContentElement) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentElement.ProtoReflect.Descriptor instead.
func (*ContentElement) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{5}
}

func (x *ContentElement) GetBlockDetails() *BlockDetails {
	if x != nil {
		return x.BlockDetails
	}
	return nil
}

func (x *ContentElement) GetExecDetails() *ExecDetails {
	if x != nil {
		return x.ExecDetails
	}
	return nil
}

func (x *ContentElement) GetMeta() *MapData {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ContentElement) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContentElement) GetAttrs() *MapData {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *ContentElement) GetDataContext() *MapData {
	if x != nil {
		return x.DataContext
	}
	return nil
}

func (x *ContentElement) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type FormattedContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MapData               `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ExecDetails   *ExecDetails           `protobuf:"bytes,2,opt,name=exec_details,json=execDetails,proto3" json:"exec_details,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormattedContent) Reset() {
	*x = FormattedContent{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormattedContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormattedContent) ProtoMessage() {}

func (x *FormattedContent) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormattedContent.ProtoReflect.Descriptor instead.
func (*FormattedContent) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{6}
}

func (x *FormattedContent) GetMeta() *MapData {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *FormattedContent) GetExecDetails() *ExecDetails {
	if x != nil {
		return x.ExecDetails
	}
	return nil
}

func (x *FormattedContent) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FormattedContent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_pluginapi_v1_content_proto protoreflect.FileDescriptor

const file_pluginapi_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x1apluginapi/v1/content.proto\x12\fpluginapi.v1\x1a\x17pluginapi/v1/data.proto\"H\n" +
	"\x15ContentProviderResult\x12/\n" +
	"\acontent\x18\x01 \x01(\v2\x15.pluginapi.v1.ContentR\acontent\"\x86\x01\n" +
	"\aContent\x128\n" +
	"\aelement\x18\x01 \x01(\v2\x1c.pluginapi.v1.ContentElementH\x00R\aelement\x128\n" +
	"\asection\x18\x02 \x01(\v2\x1c.pluginapi.v1.ContentSectionH\x00R\asectionB\a\n" +
	"\x05value\"t\n" +
	"\fBlockDetails\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06runner\x18\x02 \x01(\tR\x06runner\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\rR\x05depth\"m\n" +
	"\vExecDetails\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12%\n" +
	"\x0eplugin_version\x18\x02 \x01(\tR\rpluginVersion\x12\x16\n" +
	"\x06runner\x18\x03 \x01(\tR\x06runner\"\xfb\x01\n" +
	"\x0eContentSection\x12?\n" +
	"\rblock_details\x18\x01 \x01(\v2\x1a.pluginapi.v1.BlockDetailsR\fblockDetails\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x15.pluginapi.v1.MapDataR\x04meta\x120\n" +
	"\x05title\x18\x03 \x01(\v2\x15.pluginapi.v1.ContentH\x00R\x05title\x88\x01\x01\x121\n" +
	"\bchildren\x18\x04 \x03(\v2\x15.pluginapi.v1.ContentR\bchildren\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\fR\x02idB\b\n" +
	"\x06_title\"\xc5\x02\n" +
	"\x0eContentElement\x12?\n" +
	"\rblock_details\x18\x01 \x01(\v2\x1a.pluginapi.v1.BlockDetailsR\fblockDetails\x12<\n" +
	"\fexec_details\x18\x02 \x01(\v2\x19.pluginapi.v1.ExecDetailsR\vexecDetails\x12)\n" +
	"\x04meta\x18\x03 \x01(\v2\x15.pluginapi.v1.MapDataR\x04meta\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12+\n" +
	"\x05attrs\x18\x05 \x01(\v2\x15.pluginapi.v1.MapDataR\x05attrs\x128\n" +
	"\fdata_context\x18\x06 \x01(\v2\x15.pluginapi.v1.MapDataR\vdataContext\x12\x0e\n" +
	"\x02id\x18\a \x01(\fR\x02id\"\xad\x01\n" +
	"\x10FormattedContent\x12)\n" +
	"\x04meta\x18\x01 \x01(\v2\x15.pluginapi.v1.MapDataR\x04meta\x12<\n" +
	"\fexec_details\x18\x02 \x01(\v2\x19.pluginapi.v1.ExecDetailsR\vexecDetails\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontentB\xba\x01\n" +
	"\x10com.pluginapi.v1B\fContentProtoP\x01ZGgithub.com/blackstork-io/blackstork-cli/plugin/pluginapi/v1;pluginapiv1\xa2\x02\x03PXX\xaa\x02\fPluginapi.V1\xca\x02\fPluginapi\\V1\xe2\x02\x18Pluginapi\\V1\\GPBMetadata\xea\x02\rPluginapi::V1b\x06proto3"

var (
	file_pluginapi_v1_content_proto_rawDescOnce sync.Once
	file_pluginapi_v1_content_proto_rawDescData []byte
)

func file_pluginapi_v1_content_proto_rawDescGZIP() []byte {
	file_pluginapi_v1_content_proto_rawDescOnce.Do(func() {
		file_pluginapi_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginapi_v1_content_proto_rawDesc), len(file_pluginapi_v1_content_proto_rawDesc)))
	})
	return file_pluginapi_v1_content_proto_rawDescData
}

var file_pluginapi_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pluginapi_v1_content_proto_goTypes = []any{
	(*ContentProviderResult)(nil), // 0: pluginapi.v1.ContentProviderResult
	(*Content)(nil),               // 1: pluginapi.v1.Content
	(*BlockDetails)(nil),          // 2: pluginapi.v1.BlockDetails
	(*ExecDetails)(nil),           // 3: pluginapi.v1.ExecDetails
	(*ContentSection)(nil),        // 4: pluginapi.v1.ContentSection
	(*ContentElement)(nil),        // 5: pluginapi.v1.ContentElement
	(*FormattedContent)(nil),      // 6: pluginapi.v1.FormattedContent
	(*MapData)(nil),               // 7: pluginapi.v1.MapData
}
var file_pluginapi_v1_content_proto_depIdxs = []int32{
	1,  // 0: pluginapi.v1.ContentProviderResult.content:type_name -> pluginapi.v1.Content
	5,  // 1: pluginapi.v1.Content.element:type_name -> pluginapi.v1.ContentElement
	4,  // 2: pluginapi.v1.Content.section:type_name -> pluginapi.v1.ContentSection
	2,  // 3: pluginapi.v1.ContentSection.block_details:type_name -> pluginapi.v1.BlockDetails
	7,  // 4: pluginapi.v1.ContentSection.meta:type_name -> pluginapi.v1.MapData
	1,  // 5: pluginapi.v1.ContentSection.title:type_name -> pluginapi.v1.Content
	1,  // 6: pluginapi.v1.ContentSection.children:type_name -> pluginapi.v1.Content
	2,  // 7: pluginapi.v1.ContentElement.block_details:type_name -> pluginapi.v1.BlockDetails
	3,  // 8: pluginapi.v1.ContentElement.exec_details:type_name -> pluginapi.v1.ExecDetails
	7,  // 9: pluginapi.v1.ContentElement.meta:type_name -> pluginapi.v1.MapData
	7,  // 10: pluginapi.v1.ContentElement.attrs:type_name -> pluginapi.v1.MapData
	7,  // 11: pluginapi.v1.ContentElement.data_context:type_name -> pluginapi.v1.MapData
	7,  // 12: pluginapi.v1.FormattedContent.meta:type_name -> pluginapi.v1.MapData
	3,  // 13: pluginapi.v1.FormattedContent.exec_details:type_name -> pluginapi.v1.ExecDetails
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pluginapi_v1_content_proto_init() }
func file_pluginapi_v1_content_proto_init() {
	if File_pluginapi_v1_content_proto != nil {
		return
	}
	file_pluginapi_v1_data_proto_init()
	file_pluginapi_v1_content_proto_msgTypes[1].OneofWrappers = []any{
		(*Content_Element)(nil),
		(*Content_Section)(nil),
	}
	file_pluginapi_v1_content_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginapi_v1_content_proto_rawDesc), len(file_pluginapi_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluginapi_v1_content_proto_goTypes,
		DependencyIndexes: file_pluginapi_v1_content_proto_depIdxs,
		MessageInfos:      file_pluginapi_v1_content_proto_msgTypes,
	}.Build()
	File_pluginapi_v1_content_proto = out.File
	file_pluginapi_v1_content_proto_goTypes = nil
	file_pluginapi_v1_content_proto_depIdxs = nil
}
