// Copyright 2026 BlackStork BV
//
// Use of this software is governed by the Business Source License included in the
// file LICENSE and at www.mariadb.com/bsl11.
//
// As of the Change Date specified in that file, in accordance with the Business
// Source License, use of this software will be governed by the Apache License,
// Version 2.0, included in the file .licenses/APACHE-2.0.txt.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluginapi/v1/document.proto

package pluginapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateName  string                 `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Content       *Content               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_pluginapi_v1_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *Document) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Document) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pluginapi_v1_document_proto protoreflect.FileDescriptor

const file_pluginapi_v1_document_proto_rawDesc = "" +
	"\n" +
	"\x1bpluginapi/v1/document.proto\x12\fpluginapi.v1\x1a\x1apluginapi/v1/content.proto\x1a\x17pluginapi/v1/data.proto\"\x88\x01\n" +
	"\bDocument\x12#\n" +
	"\rtemplate_name\x18\x01 \x01(\tR\ftemplateName\x12/\n" +
	"\acontent\x18\x02 \x01(\v2\x15.pluginapi.v1.ContentR\acontent\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.pluginapi.v1.DataR\x04dataB\xbb\x01\n" +
	"\x10com.pluginapi.v1B\rDocumentProtoP\x01ZGgithub.com/blackstork-io/blackstork-cli/plugin/pluginapi/v1;pluginapiv1\xa2\x02\x03PXX\xaa\x02\fPluginapi.V1\xca\x02\fPluginapi\\V1\xe2\x02\x18Pluginapi\\V1\\GPBMetadata\xea\x02\rPluginapi::V1b\x06proto3"

var (
	file_pluginapi_v1_document_proto_rawDescOnce sync.Once
	file_pluginapi_v1_document_proto_rawDescData []byte
)

func file_pluginapi_v1_document_proto_rawDescGZIP() []byte {
	file_pluginapi_v1_document_proto_rawDescOnce.Do(func() {
		file_pluginapi_v1_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginapi_v1_document_proto_rawDesc), len(file_pluginapi_v1_document_proto_rawDesc)))
	})
	return file_pluginapi_v1_document_proto_rawDescData
}

var file_pluginapi_v1_document_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pluginapi_v1_document_proto_goTypes = []any{
	(*Document)(nil), // 0: pluginapi.v1.Document
	(*Content)(nil),  // 1: pluginapi.v1.Content
	(*Data)(nil),     // 2: pluginapi.v1.Data
}
var file_pluginapi_v1_document_proto_depIdxs = []int32{
	1, // 0: pluginapi.v1.Document.content:type_name -> pluginapi.v1.Content
	2, // 1: pluginapi.v1.Document.data:type_name -> pluginapi.v1.Data
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pluginapi_v1_document_proto_init() }
func file_pluginapi_v1_document_proto_init() {
	if File_pluginapi_v1_document_proto != nil {
		return
	}
	file_pluginapi_v1_content_proto_init()
	file_pluginapi_v1_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginapi_v1_document_proto_rawDesc), len(file_pluginapi_v1_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluginapi_v1_document_proto_goTypes,
		DependencyIndexes: file_pluginapi_v1_document_proto_depIdxs,
		MessageInfos:      file_pluginapi_v1_document_proto_msgTypes,
	}.Build()
	File_pluginapi_v1_document_proto = out.File
	file_pluginapi_v1_document_proto_goTypes = nil
	file_pluginapi_v1_document_proto_depIdxs = nil
}
