// Copyright 2026 BlackStork BV
//
// Use of this software is governed by the Business Source License included in the
// file LICENSE and at www.mariadb.com/bsl11.
//
// As of the Change Date specified in that file, in accordance with the Business
// Source License, use of this software will be governed by the Apache License,
// Version 2.0, included in the file .licenses/APACHE-2.0.txt.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluginapi/v1/plugin.proto

package pluginapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *Schema                `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetSchemaResponse) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type RetrieveDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Args          *Block                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Config        *Block                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveDataRequest) Reset() {
	*x = RetrieveDataRequest{}
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDataRequest) ProtoMessage() {}

func (x *RetrieveDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDataRequest.ProtoReflect.Descriptor instead.
func (*RetrieveDataRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveDataRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RetrieveDataRequest) GetArgs() *Block {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RetrieveDataRequest) GetConfig() *Block {
	if x != nil {
		return x.Config
	}
	return nil
}

type RetrieveDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Data                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveDataResponse) Reset() {
	*x = RetrieveDataResponse{}
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDataResponse) ProtoMessage() {}

func (x *RetrieveDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDataResponse.ProtoReflect.Descriptor instead.
func (*RetrieveDataResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveDataResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RetrieveDataResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type ProvideContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Args          *Block                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Config        *Block                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	DataContext   *MapData               `protobuf:"bytes,4,opt,name=data_context,json=dataContext,proto3" json:"data_context,omitempty"`
	ContentId     uint32                 `protobuf:"varint,5,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideContentRequest) Reset() {
	*x = ProvideContentRequest{}
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideContentRequest) ProtoMessage() {}

func (x *ProvideContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideContentRequest.ProtoReflect.Descriptor instead.
func (*ProvideContentRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ProvideContentRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProvideContentRequest) GetArgs() *Block {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProvideContentRequest) GetConfig() *Block {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ProvideContentRequest) GetDataContext() *MapData {
	if x != nil {
		return x.DataContext
	}
	return nil
}

func (x *ProvideContentRequest) GetContentId() uint32 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

type ProvideContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ContentProviderResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideContentResponse) Reset() {
	*x = ProvideContentResponse{}
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideContentResponse) ProtoMessage() {}

func (x *ProvideContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideContentResponse.ProtoReflect.Descriptor instead.
func (*ProvideContentResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ProvideContentResponse) GetResult() *ContentProviderResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProvideContentResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type FormatContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formatter     string                 `protobuf:"bytes,1,opt,name=formatter,proto3" json:"formatter,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Args          *Block                 `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	Config        *Block                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	DataContext   *MapData               `protobuf:"bytes,5,opt,name=data_context,json=dataContext,proto3" json:"data_context,omitempty"`
	Content       *MapData               `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatContentRequest) Reset() {
	*x = FormatContentRequest{}
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatContentRequest) ProtoMessage() {}

func (x *FormatContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatContentRequest.ProtoReflect.Descriptor instead.
func (*FormatContentRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *FormatContentRequest) GetFormatter() string {
	if x != nil {
		return x.Formatter
	}
	return ""
}

func (x *FormatContentRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FormatContentRequest) GetArgs() *Block {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *FormatContentRequest) GetConfig() *Block {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *FormatContentRequest) GetDataContext() *MapData {
	if x != nil {
		return x.DataContext
	}
	return nil
}

func (x *FormatContentRequest) GetContent() *MapData {
	if x != nil {
		return x.Content
	}
	return nil
}

type FormatContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *FormattedContent      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatContentResponse) Reset() {
	*x = FormatContentResponse{}
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatContentResponse) ProtoMessage() {}

func (x *FormatContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatContentResponse.ProtoReflect.Descriptor instead.
func (*FormatContentResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *FormatContentResponse) GetResult() *FormattedContent {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FormatContentResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type PublishRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Publisher        string                 `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Args             *Block                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Config           *Block                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	DataContext      *MapData               `protobuf:"bytes,4,opt,name=data_context,json=dataContext,proto3" json:"data_context,omitempty"`
	FormattedContent *FormattedContent      `protobuf:"bytes,5,opt,name=formatted_content,json=formattedContent,proto3,oneof" json:"formatted_content,omitempty"`
	Content          *Content               `protobuf:"bytes,6,opt,name=content,proto3,oneof" json:"content,omitempty"`
	DocumentName     string                 `protobuf:"bytes,7,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PublishRequest) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *PublishRequest) GetArgs() *Block {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *PublishRequest) GetConfig() *Block {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PublishRequest) GetDataContext() *MapData {
	if x != nil {
		return x.DataContext
	}
	return nil
}

func (x *PublishRequest) GetFormattedContent() *FormattedContent {
	if x != nil {
		return x.FormattedContent
	}
	return nil
}

func (x *PublishRequest) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PublishRequest) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PublishResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

var File_pluginapi_v1_plugin_proto protoreflect.FileDescriptor

const file_pluginapi_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x19pluginapi/v1/plugin.proto\x12\fpluginapi.v1\x1a\x1apluginapi/v1/content.proto\x1a\x17pluginapi/v1/data.proto\x1a\x16pluginapi/v1/hcl.proto\x1a\x19pluginapi/v1/schema.proto\x1a\x1bpluginapi/v1/dataspec.proto\"\x12\n" +
	"\x10GetSchemaRequest\"A\n" +
	"\x11GetSchemaResponse\x12,\n" +
	"\x06schema\x18\x01 \x01(\v2\x14.pluginapi.v1.SchemaR\x06schema\"\x83\x01\n" +
	"\x13RetrieveDataRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12'\n" +
	"\x04args\x18\x02 \x01(\v2\x13.pluginapi.v1.BlockR\x04args\x12+\n" +
	"\x06config\x18\x03 \x01(\v2\x13.pluginapi.v1.BlockR\x06config\"z\n" +
	"\x14RetrieveDataResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.pluginapi.v1.DataR\x04data\x12:\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x18.pluginapi.v1.DiagnosticR\vdiagnostics\"\xe2\x01\n" +
	"\x15ProvideContentRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12'\n" +
	"\x04args\x18\x02 \x01(\v2\x13.pluginapi.v1.BlockR\x04args\x12+\n" +
	"\x06config\x18\x03 \x01(\v2\x13.pluginapi.v1.BlockR\x06config\x128\n" +
	"\fdata_context\x18\x04 \x01(\v2\x15.pluginapi.v1.MapDataR\vdataContext\x12\x1d\n" +
	"\n" +
	"content_id\x18\x05 \x01(\rR\tcontentId\"\x91\x01\n" +
	"\x16ProvideContentResponse\x12;\n" +
	"\x06result\x18\x01 \x01(\v2#.pluginapi.v1.ContentProviderResultR\x06result\x12:\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x18.pluginapi.v1.DiagnosticR\vdiagnostics\"\x8d\x02\n" +
	"\x14FormatContentRequest\x12\x1c\n" +
	"\tformatter\x18\x01 \x01(\tR\tformatter\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12'\n" +
	"\x04args\x18\x03 \x01(\v2\x13.pluginapi.v1.BlockR\x04args\x12+\n" +
	"\x06config\x18\x04 \x01(\v2\x13.pluginapi.v1.BlockR\x06config\x128\n" +
	"\fdata_context\x18\x05 \x01(\v2\x15.pluginapi.v1.MapDataR\vdataContext\x12/\n" +
	"\acontent\x18\x06 \x01(\v2\x15.pluginapi.v1.MapDataR\acontent\"\x8b\x01\n" +
	"\x15FormatContentResponse\x126\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.pluginapi.v1.FormattedContentR\x06result\x12:\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x18.pluginapi.v1.DiagnosticR\vdiagnostics\"\x8d\x03\n" +
	"\x0ePublishRequest\x12\x1c\n" +
	"\tpublisher\x18\x01 \x01(\tR\tpublisher\x12'\n" +
	"\x04args\x18\x02 \x01(\v2\x13.pluginapi.v1.BlockR\x04args\x12+\n" +
	"\x06config\x18\x03 \x01(\v2\x13.pluginapi.v1.BlockR\x06config\x128\n" +
	"\fdata_context\x18\x04 \x01(\v2\x15.pluginapi.v1.MapDataR\vdataContext\x12P\n" +
	"\x11formatted_content\x18\x05 \x01(\v2\x1e.pluginapi.v1.FormattedContentH\x00R\x10formattedContent\x88\x01\x01\x124\n" +
	"\acontent\x18\x06 \x01(\v2\x15.pluginapi.v1.ContentH\x01R\acontent\x88\x01\x01\x12#\n" +
	"\rdocument_name\x18\a \x01(\tR\fdocumentNameB\x14\n" +
	"\x12_formatted_contentB\n" +
	"\n" +
	"\b_content\"M\n" +
	"\x0fPublishResponse\x12:\n" +
	"\vdiagnostics\x18\x01 \x03(\v2\x18.pluginapi.v1.DiagnosticR\vdiagnostics2\xbd\x03\n" +
	"\rPluginService\x12N\n" +
	"\tGetSchema\x12\x1e.pluginapi.v1.GetSchemaRequest\x1a\x1f.pluginapi.v1.GetSchemaResponse\"\x00\x12W\n" +
	"\fRetrieveData\x12!.pluginapi.v1.RetrieveDataRequest\x1a\".pluginapi.v1.RetrieveDataResponse\"\x00\x12]\n" +
	"\x0eProvideContent\x12#.pluginapi.v1.ProvideContentRequest\x1a$.pluginapi.v1.ProvideContentResponse\"\x00\x12Z\n" +
	"\rFormatContent\x12\".pluginapi.v1.FormatContentRequest\x1a#.pluginapi.v1.FormatContentResponse\"\x00\x12H\n" +
	"\aPublish\x12\x1c.pluginapi.v1.PublishRequest\x1a\x1d.pluginapi.v1.PublishResponse\"\x00B\xb9\x01\n" +
	"\x10com.pluginapi.v1B\vPluginProtoP\x01ZGgithub.com/blackstork-io/blackstork-cli/plugin/pluginapi/v1;pluginapiv1\xa2\x02\x03PXX\xaa\x02\fPluginapi.V1\xca\x02\fPluginapi\\V1\xe2\x02\x18Pluginapi\\V1\\GPBMetadata\xea\x02\rPluginapi::V1b\x06proto3"

var (
	file_pluginapi_v1_plugin_proto_rawDescOnce sync.Once
	file_pluginapi_v1_plugin_proto_rawDescData []byte
)

func file_pluginapi_v1_plugin_proto_rawDescGZIP() []byte {
	file_pluginapi_v1_plugin_proto_rawDescOnce.Do(func() {
		file_pluginapi_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginapi_v1_plugin_proto_rawDesc), len(file_pluginapi_v1_plugin_proto_rawDesc)))
	})
	return file_pluginapi_v1_plugin_proto_rawDescData
}

var file_pluginapi_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pluginapi_v1_plugin_proto_goTypes = []any{
	(*GetSchemaRequest)(nil),       // 0: pluginapi.v1.GetSchemaRequest
	(*GetSchemaResponse)(nil),      // 1: pluginapi.v1.GetSchemaResponse
	(*RetrieveDataRequest)(nil),    // 2: pluginapi.v1.RetrieveDataRequest
	(*RetrieveDataResponse)(nil),   // 3: pluginapi.v1.RetrieveDataResponse
	(*ProvideContentRequest)(nil),  // 4: pluginapi.v1.ProvideContentRequest
	(*ProvideContentResponse)(nil), // 5: pluginapi.v1.ProvideContentResponse
	(*FormatContentRequest)(nil),   // 6: pluginapi.v1.FormatContentRequest
	(*FormatContentResponse)(nil),  // 7: pluginapi.v1.FormatContentResponse
	(*PublishRequest)(nil),         // 8: pluginapi.v1.PublishRequest
	(*PublishResponse)(nil),        // 9: pluginapi.v1.PublishResponse
	(*Schema)(nil),                 // 10: pluginapi.v1.Schema
	(*Block)(nil),                  // 11: pluginapi.v1.Block
	(*Data)(nil),                   // 12: pluginapi.v1.Data
	(*Diagnostic)(nil),             // 13: pluginapi.v1.Diagnostic
	(*MapData)(nil),                // 14: pluginapi.v1.MapData
	(*ContentProviderResult)(nil),  // 15: pluginapi.v1.ContentProviderResult
	(*FormattedContent)(nil),       // 16: pluginapi.v1.FormattedContent
	(*Content)(nil),                // 17: pluginapi.v1.Content
}
var file_pluginapi_v1_plugin_proto_depIdxs = []int32{
	10, // 0: pluginapi.v1.GetSchemaResponse.schema:type_name -> pluginapi.v1.Schema
	11, // 1: pluginapi.v1.RetrieveDataRequest.args:type_name -> pluginapi.v1.Block
	11, // 2: pluginapi.v1.RetrieveDataRequest.config:type_name -> pluginapi.v1.Block
	12, // 3: pluginapi.v1.RetrieveDataResponse.data:type_name -> pluginapi.v1.Data
	13, // 4: pluginapi.v1.RetrieveDataResponse.diagnostics:type_name -> pluginapi.v1.Diagnostic
	11, // 5: pluginapi.v1.ProvideContentRequest.args:type_name -> pluginapi.v1.Block
	11, // 6: pluginapi.v1.ProvideContentRequest.config:type_name -> pluginapi.v1.Block
	14, // 7: pluginapi.v1.ProvideContentRequest.data_context:type_name -> pluginapi.v1.MapData
	15, // 8: pluginapi.v1.ProvideContentResponse.result:type_name -> pluginapi.v1.ContentProviderResult
	13, // 9: pluginapi.v1.ProvideContentResponse.diagnostics:type_name -> pluginapi.v1.Diagnostic
	11, // 10: pluginapi.v1.FormatContentRequest.args:type_name -> pluginapi.v1.Block
	11, // 11: pluginapi.v1.FormatContentRequest.config:type_name -> pluginapi.v1.Block
	14, // 12: pluginapi.v1.FormatContentRequest.data_context:type_name -> pluginapi.v1.MapData
	14, // 13: pluginapi.v1.FormatContentRequest.content:type_name -> pluginapi.v1.MapData
	16, // 14: pluginapi.v1.FormatContentResponse.result:type_name -> pluginapi.v1.FormattedContent
	13, // 15: pluginapi.v1.FormatContentResponse.diagnostics:type_name -> pluginapi.v1.Diagnostic
	11, // 16: pluginapi.v1.PublishRequest.args:type_name -> pluginapi.v1.Block
	11, // 17: pluginapi.v1.PublishRequest.config:type_name -> pluginapi.v1.Block
	14, // 18: pluginapi.v1.PublishRequest.data_context:type_name -> pluginapi.v1.MapData
	16, // 19: pluginapi.v1.PublishRequest.formatted_content:type_name -> pluginapi.v1.FormattedContent
	17, // 20: pluginapi.v1.PublishRequest.content:type_name -> pluginapi.v1.Content
	13, // 21: pluginapi.v1.PublishResponse.diagnostics:type_name -> pluginapi.v1.Diagnostic
	0,  // 22: pluginapi.v1.PluginService.GetSchema:input_type -> pluginapi.v1.GetSchemaRequest
	2,  // 23: pluginapi.v1.PluginService.RetrieveData:input_type -> pluginapi.v1.RetrieveDataRequest
	4,  // 24: pluginapi.v1.PluginService.ProvideContent:input_type -> pluginapi.v1.ProvideContentRequest
	6,  // 25: pluginapi.v1.PluginService.FormatContent:input_type -> pluginapi.v1.FormatContentRequest
	8,  // 26: pluginapi.v1.PluginService.Publish:input_type -> pluginapi.v1.PublishRequest
	1,  // 27: pluginapi.v1.PluginService.GetSchema:output_type -> pluginapi.v1.GetSchemaResponse
	3,  // 28: pluginapi.v1.PluginService.RetrieveData:output_type -> pluginapi.v1.RetrieveDataResponse
	5,  // 29: pluginapi.v1.PluginService.ProvideContent:output_type -> pluginapi.v1.ProvideContentResponse
	7,  // 30: pluginapi.v1.PluginService.FormatContent:output_type -> pluginapi.v1.FormatContentResponse
	9,  // 31: pluginapi.v1.PluginService.Publish:output_type -> pluginapi.v1.PublishResponse
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_pluginapi_v1_plugin_proto_init() }
func file_pluginapi_v1_plugin_proto_init() {
	if File_pluginapi_v1_plugin_proto != nil {
		return
	}
	file_pluginapi_v1_content_proto_init()
	file_pluginapi_v1_data_proto_init()
	file_pluginapi_v1_hcl_proto_init()
	file_pluginapi_v1_schema_proto_init()
	file_pluginapi_v1_dataspec_proto_init()
	file_pluginapi_v1_plugin_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginapi_v1_plugin_proto_rawDesc), len(file_pluginapi_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluginapi_v1_plugin_proto_goTypes,
		DependencyIndexes: file_pluginapi_v1_plugin_proto_depIdxs,
		MessageInfos:      file_pluginapi_v1_plugin_proto_msgTypes,
	}.Build()
	File_pluginapi_v1_plugin_proto = out.File
	file_pluginapi_v1_plugin_proto_goTypes = nil
	file_pluginapi_v1_plugin_proto_depIdxs = nil
}
