// Copyright 2026 BlackStork BV
//
// Use of this software is governed by the Business Source License included in the
// file LICENSE and at www.mariadb.com/bsl11.
//
// As of the Change Date specified in that file, in accordance with the Business
// Source License, use of this software will be governed by the Apache License,
// Version 2.0, included in the file .licenses/APACHE-2.0.txt.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluginapi/v1/schema.proto

package pluginapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Schema struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Plugin components
	DataSources      map[string]*DataSourceSchema      `protobuf:"bytes,3,rep,name=data_sources,json=dataSources,proto3" json:"data_sources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentProviders map[string]*ContentProviderSchema `protobuf:"bytes,4,rep,name=content_providers,json=contentProviders,proto3" json:"content_providers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Publishers       map[string]*PublisherSchema       `protobuf:"bytes,7,rep,name=publishers,proto3" json:"publishers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Formatters       map[string]*FormatterSchema       `protobuf:"bytes,8,rep,name=formatters,proto3" json:"formatters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Doc              string                            `protobuf:"bytes,5,opt,name=doc,proto3" json:"doc,omitempty"`
	Tags             []string                          `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_pluginapi_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Schema) GetDataSources() map[string]*DataSourceSchema {
	if x != nil {
		return x.DataSources
	}
	return nil
}

func (x *Schema) GetContentProviders() map[string]*ContentProviderSchema {
	if x != nil {
		return x.ContentProviders
	}
	return nil
}

func (x *Schema) GetPublishers() map[string]*PublisherSchema {
	if x != nil {
		return x.Publishers
	}
	return nil
}

func (x *Schema) GetFormatters() map[string]*FormatterSchema {
	if x != nil {
		return x.Formatters
	}
	return nil
}

func (x *Schema) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Schema) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DataSourceSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          *BlockSpec             `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	Config        *BlockSpec             `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Doc           string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceSchema) Reset() {
	*x = DataSourceSchema{}
	mi := &file_pluginapi_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceSchema) ProtoMessage() {}

func (x *DataSourceSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceSchema.ProtoReflect.Descriptor instead.
func (*DataSourceSchema) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *DataSourceSchema) GetArgs() *BlockSpec {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *DataSourceSchema) GetConfig() *BlockSpec {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DataSourceSchema) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *DataSourceSchema) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ContentProviderSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          *BlockSpec             `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	Config        *BlockSpec             `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Doc           string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentProviderSchema) Reset() {
	*x = ContentProviderSchema{}
	mi := &file_pluginapi_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentProviderSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentProviderSchema) ProtoMessage() {}

func (x *ContentProviderSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentProviderSchema.ProtoReflect.Descriptor instead.
func (*ContentProviderSchema) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *ContentProviderSchema) GetArgs() *BlockSpec {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ContentProviderSchema) GetConfig() *BlockSpec {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ContentProviderSchema) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *ContentProviderSchema) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PublisherSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          *BlockSpec             `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	Config        *BlockSpec             `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Doc           string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Formats       []string               `protobuf:"bytes,5,rep,name=formats,proto3" json:"formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherSchema) Reset() {
	*x = PublisherSchema{}
	mi := &file_pluginapi_v1_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherSchema) ProtoMessage() {}

func (x *PublisherSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherSchema.ProtoReflect.Descriptor instead.
func (*PublisherSchema) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *PublisherSchema) GetArgs() *BlockSpec {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *PublisherSchema) GetConfig() *BlockSpec {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PublisherSchema) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *PublisherSchema) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PublisherSchema) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

type FormatterSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          *BlockSpec             `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	Config        *BlockSpec             `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Doc           string                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	FileExt       string                 `protobuf:"bytes,5,opt,name=file_ext,json=fileExt,proto3" json:"file_ext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatterSchema) Reset() {
	*x = FormatterSchema{}
	mi := &file_pluginapi_v1_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatterSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatterSchema) ProtoMessage() {}

func (x *FormatterSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatterSchema.ProtoReflect.Descriptor instead.
func (*FormatterSchema) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_schema_proto_rawDescGZIP(), []int{4}
}

func (x *FormatterSchema) GetArgs() *BlockSpec {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *FormatterSchema) GetConfig() *BlockSpec {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *FormatterSchema) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *FormatterSchema) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FormatterSchema) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

var File_pluginapi_v1_schema_proto protoreflect.FileDescriptor

const file_pluginapi_v1_schema_proto_rawDesc = "" +
	"\n" +
	"\x19pluginapi/v1/schema.proto\x12\fpluginapi.v1\x1a\x1bpluginapi/v1/dataspec.proto\"\x91\x06\n" +
	"\x06Schema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12H\n" +
	"\fdata_sources\x18\x03 \x03(\v2%.pluginapi.v1.Schema.DataSourcesEntryR\vdataSources\x12W\n" +
	"\x11content_providers\x18\x04 \x03(\v2*.pluginapi.v1.Schema.ContentProvidersEntryR\x10contentProviders\x12D\n" +
	"\n" +
	"publishers\x18\a \x03(\v2$.pluginapi.v1.Schema.PublishersEntryR\n" +
	"publishers\x12D\n" +
	"\n" +
	"formatters\x18\b \x03(\v2$.pluginapi.v1.Schema.FormattersEntryR\n" +
	"formatters\x12\x10\n" +
	"\x03doc\x18\x05 \x01(\tR\x03doc\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x1a^\n" +
	"\x10DataSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.pluginapi.v1.DataSourceSchemaR\x05value:\x028\x01\x1ah\n" +
	"\x15ContentProvidersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.pluginapi.v1.ContentProviderSchemaR\x05value:\x028\x01\x1a\\\n" +
	"\x0fPublishersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.pluginapi.v1.PublisherSchemaR\x05value:\x028\x01\x1a\\\n" +
	"\x0fFormattersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.pluginapi.v1.FormatterSchemaR\x05value:\x028\x01\"\x96\x01\n" +
	"\x10DataSourceSchema\x12+\n" +
	"\x04args\x18\x01 \x01(\v2\x17.pluginapi.v1.BlockSpecR\x04args\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.pluginapi.v1.BlockSpecR\x06config\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\x9b\x01\n" +
	"\x15ContentProviderSchema\x12+\n" +
	"\x04args\x18\x01 \x01(\v2\x17.pluginapi.v1.BlockSpecR\x04args\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.pluginapi.v1.BlockSpecR\x06config\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\xaf\x01\n" +
	"\x0fPublisherSchema\x12+\n" +
	"\x04args\x18\x01 \x01(\v2\x17.pluginapi.v1.BlockSpecR\x04args\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.pluginapi.v1.BlockSpecR\x06config\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x18\n" +
	"\aformats\x18\x05 \x03(\tR\aformats\"\xb4\x01\n" +
	"\x0fFormatterSchema\x12+\n" +
	"\x04args\x18\x01 \x01(\v2\x17.pluginapi.v1.BlockSpecR\x04args\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.pluginapi.v1.BlockSpecR\x06config\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\tR\x03doc\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x19\n" +
	"\bfile_ext\x18\x05 \x01(\tR\afileExtB\xb9\x01\n" +
	"\x10com.pluginapi.v1B\vSchemaProtoP\x01ZGgithub.com/blackstork-io/blackstork-cli/plugin/pluginapi/v1;pluginapiv1\xa2\x02\x03PXX\xaa\x02\fPluginapi.V1\xca\x02\fPluginapi\\V1\xe2\x02\x18Pluginapi\\V1\\GPBMetadata\xea\x02\rPluginapi::V1b\x06proto3"

var (
	file_pluginapi_v1_schema_proto_rawDescOnce sync.Once
	file_pluginapi_v1_schema_proto_rawDescData []byte
)

func file_pluginapi_v1_schema_proto_rawDescGZIP() []byte {
	file_pluginapi_v1_schema_proto_rawDescOnce.Do(func() {
		file_pluginapi_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginapi_v1_schema_proto_rawDesc), len(file_pluginapi_v1_schema_proto_rawDesc)))
	})
	return file_pluginapi_v1_schema_proto_rawDescData
}

var file_pluginapi_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pluginapi_v1_schema_proto_goTypes = []any{
	(*Schema)(nil),                // 0: pluginapi.v1.Schema
	(*DataSourceSchema)(nil),      // 1: pluginapi.v1.DataSourceSchema
	(*ContentProviderSchema)(nil), // 2: pluginapi.v1.ContentProviderSchema
	(*PublisherSchema)(nil),       // 3: pluginapi.v1.PublisherSchema
	(*FormatterSchema)(nil),       // 4: pluginapi.v1.FormatterSchema
	nil,                           // 5: pluginapi.v1.Schema.DataSourcesEntry
	nil,                           // 6: pluginapi.v1.Schema.ContentProvidersEntry
	nil,                           // 7: pluginapi.v1.Schema.PublishersEntry
	nil,                           // 8: pluginapi.v1.Schema.FormattersEntry
	(*BlockSpec)(nil),             // 9: pluginapi.v1.BlockSpec
}
var file_pluginapi_v1_schema_proto_depIdxs = []int32{
	5,  // 0: pluginapi.v1.Schema.data_sources:type_name -> pluginapi.v1.Schema.DataSourcesEntry
	6,  // 1: pluginapi.v1.Schema.content_providers:type_name -> pluginapi.v1.Schema.ContentProvidersEntry
	7,  // 2: pluginapi.v1.Schema.publishers:type_name -> pluginapi.v1.Schema.PublishersEntry
	8,  // 3: pluginapi.v1.Schema.formatters:type_name -> pluginapi.v1.Schema.FormattersEntry
	9,  // 4: pluginapi.v1.DataSourceSchema.args:type_name -> pluginapi.v1.BlockSpec
	9,  // 5: pluginapi.v1.DataSourceSchema.config:type_name -> pluginapi.v1.BlockSpec
	9,  // 6: pluginapi.v1.ContentProviderSchema.args:type_name -> pluginapi.v1.BlockSpec
	9,  // 7: pluginapi.v1.ContentProviderSchema.config:type_name -> pluginapi.v1.BlockSpec
	9,  // 8: pluginapi.v1.PublisherSchema.args:type_name -> pluginapi.v1.BlockSpec
	9,  // 9: pluginapi.v1.PublisherSchema.config:type_name -> pluginapi.v1.BlockSpec
	9,  // 10: pluginapi.v1.FormatterSchema.args:type_name -> pluginapi.v1.BlockSpec
	9,  // 11: pluginapi.v1.FormatterSchema.config:type_name -> pluginapi.v1.BlockSpec
	1,  // 12: pluginapi.v1.Schema.DataSourcesEntry.value:type_name -> pluginapi.v1.DataSourceSchema
	2,  // 13: pluginapi.v1.Schema.ContentProvidersEntry.value:type_name -> pluginapi.v1.ContentProviderSchema
	3,  // 14: pluginapi.v1.Schema.PublishersEntry.value:type_name -> pluginapi.v1.PublisherSchema
	4,  // 15: pluginapi.v1.Schema.FormattersEntry.value:type_name -> pluginapi.v1.FormatterSchema
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pluginapi_v1_schema_proto_init() }
func file_pluginapi_v1_schema_proto_init() {
	if File_pluginapi_v1_schema_proto != nil {
		return
	}
	file_pluginapi_v1_dataspec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginapi_v1_schema_proto_rawDesc), len(file_pluginapi_v1_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluginapi_v1_schema_proto_goTypes,
		DependencyIndexes: file_pluginapi_v1_schema_proto_depIdxs,
		MessageInfos:      file_pluginapi_v1_schema_proto_msgTypes,
	}.Build()
	File_pluginapi_v1_schema_proto = out.File
	file_pluginapi_v1_schema_proto_goTypes = nil
	file_pluginapi_v1_schema_proto_depIdxs = nil
}
