// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pluginapi/v1/content.proto

package pluginapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentProviderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentProviderResult) Reset() {
	*x = ContentProviderResult{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentProviderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentProviderResult) ProtoMessage() {}

func (x *ContentProviderResult) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentProviderResult.ProtoReflect.Descriptor instead.
func (*ContentProviderResult) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *ContentProviderResult) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Content_Element
	//	*Content_Section
	//	*Content_Empty
	Value         isContent_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *Content) GetValue() isContent_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Content) GetElement() *ContentElement {
	if x != nil {
		if x, ok := x.Value.(*Content_Element); ok {
			return x.Element
		}
	}
	return nil
}

func (x *Content) GetSection() *ContentSection {
	if x != nil {
		if x, ok := x.Value.(*Content_Section); ok {
			return x.Section
		}
	}
	return nil
}

func (x *Content) GetEmpty() *ContentEmpty {
	if x != nil {
		if x, ok := x.Value.(*Content_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

type isContent_Value interface {
	isContent_Value()
}

type Content_Element struct {
	Element *ContentElement `protobuf:"bytes,1,opt,name=element,proto3,oneof"`
}

type Content_Section struct {
	Section *ContentSection `protobuf:"bytes,2,opt,name=section,proto3,oneof"`
}

type Content_Empty struct {
	Empty *ContentEmpty `protobuf:"bytes,3,opt,name=empty,proto3,oneof"`
}

func (*Content_Element) isContent_Value() {}

func (*Content_Section) isContent_Value() {}

func (*Content_Empty) isContent_Value() {}

type BlockSelf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	PluginVersion string                 `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	ProviderName  string                 `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSelf) Reset() {
	*x = BlockSelf{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSelf) ProtoMessage() {}

func (x *BlockSelf) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSelf.ProtoReflect.Descriptor instead.
func (*BlockSelf) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *BlockSelf) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *BlockSelf) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *BlockSelf) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *BlockSelf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ContentSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          *BlockSelf             `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Meta          *MapData               `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Children      []*Content             `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentSection) Reset() {
	*x = ContentSection{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentSection) ProtoMessage() {}

func (x *ContentSection) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentSection.ProtoReflect.Descriptor instead.
func (*ContentSection) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *ContentSection) GetSelf() *BlockSelf {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *ContentSection) GetMeta() *MapData {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ContentSection) GetChildren() []*Content {
	if x != nil {
		return x.Children
	}
	return nil
}

type ContentElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          *BlockSelf             `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Meta          *MapData               `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Attrs         *MapData               `protobuf:"bytes,4,opt,name=attrs,proto3" json:"attrs,omitempty"`
	DataContext   *MapData               `protobuf:"bytes,5,opt,name=data_context,json=dataContext,proto3" json:"data_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentElement) Reset() {
	*x = ContentElement{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentElement) ProtoMessage() {}

func (x *ContentElement) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentElement.ProtoReflect.Descriptor instead.
func (*ContentElement) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *ContentElement) GetSelf() *BlockSelf {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *ContentElement) GetMeta() *MapData {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ContentElement) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContentElement) GetAttrs() *MapData {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *ContentElement) GetDataContext() *MapData {
	if x != nil {
		return x.DataContext
	}
	return nil
}

type ContentEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          *BlockSelf             `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Meta          *MapData               `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentEmpty) Reset() {
	*x = ContentEmpty{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentEmpty) ProtoMessage() {}

func (x *ContentEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentEmpty.ProtoReflect.Descriptor instead.
func (*ContentEmpty) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{5}
}

func (x *ContentEmpty) GetSelf() *BlockSelf {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *ContentEmpty) GetMeta() *MapData {
	if x != nil {
		return x.Meta
	}
	return nil
}

type FormattedContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          *BlockSelf             `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Meta          *MapData               `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormattedContent) Reset() {
	*x = FormattedContent{}
	mi := &file_pluginapi_v1_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormattedContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormattedContent) ProtoMessage() {}

func (x *FormattedContent) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormattedContent.ProtoReflect.Descriptor instead.
func (*FormattedContent) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_content_proto_rawDescGZIP(), []int{6}
}

func (x *FormattedContent) GetSelf() *BlockSelf {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *FormattedContent) GetMeta() *MapData {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *FormattedContent) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FormattedContent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_pluginapi_v1_content_proto protoreflect.FileDescriptor

const file_pluginapi_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x1apluginapi/v1/content.proto\x12\fpluginapi.v1\x1a\x17pluginapi/v1/data.proto\"H\n" +
	"\x15ContentProviderResult\x12/\n" +
	"\acontent\x18\x01 \x01(\v2\x15.pluginapi.v1.ContentR\acontent\"\xba\x01\n" +
	"\aContent\x128\n" +
	"\aelement\x18\x01 \x01(\v2\x1c.pluginapi.v1.ContentElementH\x00R\aelement\x128\n" +
	"\asection\x18\x02 \x01(\v2\x1c.pluginapi.v1.ContentSectionH\x00R\asection\x122\n" +
	"\x05empty\x18\x03 \x01(\v2\x1a.pluginapi.v1.ContentEmptyH\x00R\x05emptyB\a\n" +
	"\x05value\"\x8c\x01\n" +
	"\tBlockSelf\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12%\n" +
	"\x0eplugin_version\x18\x02 \x01(\tR\rpluginVersion\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\x9b\x01\n" +
	"\x0eContentSection\x12+\n" +
	"\x04self\x18\x01 \x01(\v2\x17.pluginapi.v1.BlockSelfR\x04self\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x15.pluginapi.v1.MapDataR\x04meta\x121\n" +
	"\bchildren\x18\x03 \x03(\v2\x15.pluginapi.v1.ContentR\bchildren\"\xe3\x01\n" +
	"\x0eContentElement\x12+\n" +
	"\x04self\x18\x01 \x01(\v2\x17.pluginapi.v1.BlockSelfR\x04self\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x15.pluginapi.v1.MapDataR\x04meta\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12+\n" +
	"\x05attrs\x18\x04 \x01(\v2\x15.pluginapi.v1.MapDataR\x05attrs\x128\n" +
	"\fdata_context\x18\x05 \x01(\v2\x15.pluginapi.v1.MapDataR\vdataContext\"f\n" +
	"\fContentEmpty\x12+\n" +
	"\x04self\x18\x01 \x01(\v2\x17.pluginapi.v1.BlockSelfR\x04self\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x15.pluginapi.v1.MapDataR\x04meta\"\x9c\x01\n" +
	"\x10FormattedContent\x12+\n" +
	"\x04self\x18\x01 \x01(\v2\x17.pluginapi.v1.BlockSelfR\x04self\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x15.pluginapi.v1.MapDataR\x04meta\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontentB\xb2\x01\n" +
	"\x10com.pluginapi.v1B\fContentProtoP\x01Z?github.com/blackstork-io/fabric/plugin/pluginapi/v1;pluginapiv1\xa2\x02\x03PXX\xaa\x02\fPluginapi.V1\xca\x02\fPluginapi\\V1\xe2\x02\x18Pluginapi\\V1\\GPBMetadata\xea\x02\rPluginapi::V1b\x06proto3"

var (
	file_pluginapi_v1_content_proto_rawDescOnce sync.Once
	file_pluginapi_v1_content_proto_rawDescData []byte
)

func file_pluginapi_v1_content_proto_rawDescGZIP() []byte {
	file_pluginapi_v1_content_proto_rawDescOnce.Do(func() {
		file_pluginapi_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginapi_v1_content_proto_rawDesc), len(file_pluginapi_v1_content_proto_rawDesc)))
	})
	return file_pluginapi_v1_content_proto_rawDescData
}

var file_pluginapi_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pluginapi_v1_content_proto_goTypes = []any{
	(*ContentProviderResult)(nil), // 0: pluginapi.v1.ContentProviderResult
	(*Content)(nil),               // 1: pluginapi.v1.Content
	(*BlockSelf)(nil),             // 2: pluginapi.v1.BlockSelf
	(*ContentSection)(nil),        // 3: pluginapi.v1.ContentSection
	(*ContentElement)(nil),        // 4: pluginapi.v1.ContentElement
	(*ContentEmpty)(nil),          // 5: pluginapi.v1.ContentEmpty
	(*FormattedContent)(nil),      // 6: pluginapi.v1.FormattedContent
	(*MapData)(nil),               // 7: pluginapi.v1.MapData
}
var file_pluginapi_v1_content_proto_depIdxs = []int32{
	1,  // 0: pluginapi.v1.ContentProviderResult.content:type_name -> pluginapi.v1.Content
	4,  // 1: pluginapi.v1.Content.element:type_name -> pluginapi.v1.ContentElement
	3,  // 2: pluginapi.v1.Content.section:type_name -> pluginapi.v1.ContentSection
	5,  // 3: pluginapi.v1.Content.empty:type_name -> pluginapi.v1.ContentEmpty
	2,  // 4: pluginapi.v1.ContentSection.self:type_name -> pluginapi.v1.BlockSelf
	7,  // 5: pluginapi.v1.ContentSection.meta:type_name -> pluginapi.v1.MapData
	1,  // 6: pluginapi.v1.ContentSection.children:type_name -> pluginapi.v1.Content
	2,  // 7: pluginapi.v1.ContentElement.self:type_name -> pluginapi.v1.BlockSelf
	7,  // 8: pluginapi.v1.ContentElement.meta:type_name -> pluginapi.v1.MapData
	7,  // 9: pluginapi.v1.ContentElement.attrs:type_name -> pluginapi.v1.MapData
	7,  // 10: pluginapi.v1.ContentElement.data_context:type_name -> pluginapi.v1.MapData
	2,  // 11: pluginapi.v1.ContentEmpty.self:type_name -> pluginapi.v1.BlockSelf
	7,  // 12: pluginapi.v1.ContentEmpty.meta:type_name -> pluginapi.v1.MapData
	2,  // 13: pluginapi.v1.FormattedContent.self:type_name -> pluginapi.v1.BlockSelf
	7,  // 14: pluginapi.v1.FormattedContent.meta:type_name -> pluginapi.v1.MapData
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pluginapi_v1_content_proto_init() }
func file_pluginapi_v1_content_proto_init() {
	if File_pluginapi_v1_content_proto != nil {
		return
	}
	file_pluginapi_v1_data_proto_init()
	file_pluginapi_v1_content_proto_msgTypes[1].OneofWrappers = []any{
		(*Content_Element)(nil),
		(*Content_Section)(nil),
		(*Content_Empty)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginapi_v1_content_proto_rawDesc), len(file_pluginapi_v1_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluginapi_v1_content_proto_goTypes,
		DependencyIndexes: file_pluginapi_v1_content_proto_depIdxs,
		MessageInfos:      file_pluginapi_v1_content_proto_msgTypes,
	}.Build()
	File_pluginapi_v1_content_proto = out.File
	file_pluginapi_v1_content_proto_goTypes = nil
	file_pluginapi_v1_content_proto_depIdxs = nil
}
