// Code generated by mockery v2.52.2. DO NOT EDIT.

package definitions_mocks

import (
	cty "github.com/zclconf/go-cty/cty"

	hclsyntax "github.com/hashicorp/hcl/v2/hclsyntax"

	mock "github.com/stretchr/testify/mock"
)

// BlockDef is an autogenerated mock type for the BlockDef type
type BlockDef struct {
	mock.Mock
}

type BlockDef_Expecter struct {
	mock *mock.Mock
}

func (_m *BlockDef) EXPECT() *BlockDef_Expecter {
	return &BlockDef_Expecter{mock: &_m.Mock}
}

// CtyType provides a mock function with no fields
func (_m *BlockDef) CtyType() cty.Type {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CtyType")
	}

	var r0 cty.Type
	if rf, ok := ret.Get(0).(func() cty.Type); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(cty.Type)
	}

	return r0
}

// BlockDef_CtyType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CtyType'
type BlockDef_CtyType_Call struct {
	*mock.Call
}

// CtyType is a helper method to define mock.On call
func (_e *BlockDef_Expecter) CtyType() *BlockDef_CtyType_Call {
	return &BlockDef_CtyType_Call{Call: _e.mock.On("CtyType")}
}

func (_c *BlockDef_CtyType_Call) Run(run func()) *BlockDef_CtyType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockDef_CtyType_Call) Return(_a0 cty.Type) *BlockDef_CtyType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlockDef_CtyType_Call) RunAndReturn(run func() cty.Type) *BlockDef_CtyType_Call {
	_c.Call.Return(run)
	return _c
}

// GetHCLBlock provides a mock function with no fields
func (_m *BlockDef) GetHCLBlock() *hclsyntax.Block {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHCLBlock")
	}

	var r0 *hclsyntax.Block
	if rf, ok := ret.Get(0).(func() *hclsyntax.Block); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hclsyntax.Block)
		}
	}

	return r0
}

// BlockDef_GetHCLBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHCLBlock'
type BlockDef_GetHCLBlock_Call struct {
	*mock.Call
}

// GetHCLBlock is a helper method to define mock.On call
func (_e *BlockDef_Expecter) GetHCLBlock() *BlockDef_GetHCLBlock_Call {
	return &BlockDef_GetHCLBlock_Call{Call: _e.mock.On("GetHCLBlock")}
}

func (_c *BlockDef_GetHCLBlock_Call) Run(run func()) *BlockDef_GetHCLBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockDef_GetHCLBlock_Call) Return(_a0 *hclsyntax.Block) *BlockDef_GetHCLBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlockDef_GetHCLBlock_Call) RunAndReturn(run func() *hclsyntax.Block) *BlockDef_GetHCLBlock_Call {
	_c.Call.Return(run)
	return _c
}

// Kind provides a mock function with no fields
func (_m *BlockDef) Kind() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kind")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BlockDef_Kind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kind'
type BlockDef_Kind_Call struct {
	*mock.Call
}

// Kind is a helper method to define mock.On call
func (_e *BlockDef_Expecter) Kind() *BlockDef_Kind_Call {
	return &BlockDef_Kind_Call{Call: _e.mock.On("Kind")}
}

func (_c *BlockDef_Kind_Call) Run(run func()) *BlockDef_Kind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BlockDef_Kind_Call) Return(_a0 string) *BlockDef_Kind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlockDef_Kind_Call) RunAndReturn(run func() string) *BlockDef_Kind_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlockDef creates a new instance of BlockDef. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockDef(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockDef {
	mock := &BlockDef{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
