syntax = "proto3";

package pluginapi.v1;

import "pluginapi/v1/data.proto";

message ContentProviderResult {
    Content  content  = 1;
}

message Content {
    oneof value {
        ContentElement element = 1;
        ContentSection section = 2;
        ContentEmpty   empty   = 3;
    };
}

message Metadata {
    string provider_name = 1;
    string provider_plugin_name = 2;
    string provider_plugin_version = 3;
}

message ContentSection {
    Metadata meta = 1;
    repeated Content children = 2;
}

message ContentElement {
    Metadata meta = 1;

    string kind = 2;

    MapData attrs = 3;
    MapData data_context = 4;
}

message ContentEmpty {
    Metadata meta = 1;
}


message FormattedContent {
    string format = 1;
    bytes content = 2;
}
