syntax = "proto3";

package pluginapi.v1;

import "pluginapi/v1/data.proto";

message ContentProviderResult {
    Content  content  = 1;
}

message Content {
    oneof value {
        ContentElement element = 1;
        ContentSection section = 2;
        ContentEmpty   empty   = 3;
    };
}

message BlockSelf {
    string plugin_name = 1;
    string plugin_version = 2;
    string provider_name = 3;
    string name = 4;
}

message ContentSection {
    BlockSelf self = 1;
    MapData meta   = 2;
    repeated Content children = 3;
}

message ContentElement {
    BlockSelf self = 1;
    MapData meta = 2;

    string kind = 3;

    MapData attrs = 4;
    MapData data_context = 5;
}

message ContentEmpty {
    BlockSelf self = 1;
    MapData meta   = 2;
}


message FormattedContent {
    BlockSelf self = 1;
    MapData meta   = 2;

    string format = 3;
    bytes content = 4;
}
