syntax = "proto3";

package pluginapi.v1;

import "pluginapi/v1/data.proto";

message ContentResult {
    Content  content  = 1;
}

message Content {
    oneof value {
        ContentElement           element = 1;
        ContentSection           section = 2;
        ContentEmpty             empty   = 3;
    };
}

message Metadata {
    string provider_name = 1;
    string provider_plugin_name = 2;
    string provider_plugin_version = 3;
}

message ContentSection {
    bytes id = 1;
    Metadata meta = 2;
    repeated Content children = 3;
}

message ContentElement {
    bytes id = 1;
    Metadata meta = 2;

    string kind = 3;

    MapData attrs = 4;
    MapData data_context = 5;
}

message ContentEmpty {
    bytes id = 1;
    Metadata meta = 2;
}


message FormattedContent {
    string format = 1;
    bytes content = 2;
}
