// Copyright 2026 BlackStork BV
//
// Use of this software is governed by the Business Source License included in the
// file LICENSE and at www.mariadb.com/bsl11.
//
// As of the Change Date specified in that file, in accordance with the Business
// Source License, use of this software will be governed by the Apache License,
// Version 2.0, included in the file .licenses/APACHE-2.0.txt.

syntax = "proto3";

package pluginapi.v1;

import "pluginapi/v1/dataspec.proto";

message Schema {
    string name    = 1;
    string version = 2;
    // Plugin components
    map<string, DataSourceSchema>       data_sources      = 3;
    map<string, ContentProviderSchema>  content_providers = 4;
    map<string, PublisherSchema>        publishers        = 7;
    map<string, FormatterSchema>        formatters        = 8;
    string                              doc               = 5;
    repeated string                     tags              = 6;
}

message DataSourceSchema {
    BlockSpec            args   = 1;
    BlockSpec            config = 2;
    string               doc    = 3;
    repeated string      tags   = 4;
}

message ContentProviderSchema {
    BlockSpec       args   = 1;
    BlockSpec       config = 2;
    string          doc    = 3;
    repeated string tags   = 4;
}

message PublisherSchema {
    BlockSpec             args    = 1;
    BlockSpec             config  = 2;
    string                doc     = 3;
    repeated string       tags    = 4;
    repeated string       formats = 5;
}

message FormatterSchema {
    BlockSpec             args     = 1;
    BlockSpec             config   = 2;
    string                doc      = 3;
    string                format   = 4;
    string                file_ext = 5;
}
