# Copyright 2026 BlackStork BV
#
# Use of this software is governed by the Business Source License included in the
# file LICENSE and at www.mariadb.com/bsl11.
#
# As of the Change Date specified in that file, in accordance with the Business
# Source License, use of this software will be governed by the Apache License,
# Version 2.0, included in the file .licenses/APACHE-2.0.txt.

name: main
# PR checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  pull_request_review:
    types: [submitted]

  workflow_dispatch:

concurrency:
  group: main-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  partial_checks:
    if: github.event_name == 'pull_request' && !github.event.pull_request.draft
    uses: ./.github/workflows/main_partial.yml

  full_checks:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    uses: ./.github/workflows/main_full.yml

  common_checks:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft

    permissions:
      # For golangci-lint
      contents: read
      pull-requests: read
      checks: write
    uses: ./.github/workflows/main_common.yml
